# Generated by Django 2.2.5 on 2020-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'initial'), (1, 'dependent'), (2, 'golang'), (3, 'unichain'), (4, 'running'), (-1, 'fail')], default=0, null=True),
        ),
    ]
