# Generated by Django 2.2.5 on 2020-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200221_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'has no start'), (1, 'initial'), (2, 'install dependent'), (3, 'install golang'), (4, 'build unichain'), (5, 'done'), (-1, 'fail')], default=0, null=True),
        ),
    ]
